feat: only username, email, password, date_of_birth, height, weight, goals are required now
Gang-de-requins/Playfit pull request #18
Opened 2024-11-01 01:21 UTC by Eowiin

## Description
[Description de la PR]

Changes for backend authentification for user's registration.

## Changement

Removal of all fields except those in the title for user's registration.
Adaptation of the tests to work with these changes.

## Commentaire

In accordance with the last group review, only essential fields are required to create a new user in database. Tests have been updated to work with these changes.

2024-11-02 08:00 UTC, Masteruuuuu reviewed
@christophechr need your opinion if possible

2024-11-02 08:00 UTC, Masteruuuuu commented on backend/playfit/authentification/models.py
Should we keep the first name and last name optional ? Or just delete them ?

2024-11-02 08:04 UTC, christophechr requested changes

2024-11-02 08:04 UTC, christophechr commented on backend/playfit/authentification/admin.py
No need for first name and last name now, I'll make sure to emphasize the RGPD rules around the end of the next week.

2024-11-02 08:04 UTC, christophechr commented on backend/playfit/authentification/migrations/0004_alter_customuser_first_name_and_more.py
Same here

2024-11-02 08:04 UTC, christophechr commented on backend/playfit/authentification/models.py
We can delete them for now

2024-11-04 12:27 UTC, christophechr approved these changes

2024-11-05 01:56 UTC, Masteruuuuu approved these changes

2024-11-05 08:25 UTC, Masteruuuuu approved these changes

2024-11-05 10:19 UTC, merged