Add Pull Request Template
Gang-de-requins/Playfit pull request #9
Opened 2024-10-14 11:19 UTC by christophechr

2024-10-14 11:31 UTC, Eowiin approved these changes

2024-10-17 11:56 UTC, Masteruuuuu approved these changes
LGTM !!

2024-10-17 12:02 UTC, Masteruuuuu requested changes
Change everything to english ? Or go to French ?

2024-10-24 06:24 UTC, christophechr commented
> Change everything to english ? Or go to French ?

French for PR and Issue is ok, I'll just comment in English

2024-10-24 06:27 UTC, merged